CREATE TABLE IF NOT EXISTS tenants(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) UNIQUE NOT NULL,
    api_key CHAR(36) UNIQUE NOT NULL,
    rate_limit_capacity INT NOT NULL DEFAULT 200,
    rate_limit_refill_per_sec INT NOT NULL DEFAULT 50,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS services(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    tenant_id BIGINT NOT NULL,
    service_name VARCHAR(255) NOT NULL,
    first_seen DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_tenant_service (tenant_id, service_name),
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);


CREATE TABLE IF NOT EXISTS spans(
    time_unix_nano BIGINT NOT NULL,
    trace_id CHAR(32) NOT NULL,
    span_id CHAR(16) NOT NULL,
    parent_span_id CHAR (16) NULL,
    tenant_id BIGINT NOT NULL,
    service_name VARCHAR(255) NOT NULL,
    span_name VARCHAR(255) NOT NULL,
    kind TINYINT NOT NULL,
    end_time_unix_nano BIGINT NOT NULL,
    duration_nano BIGINT NOT NULL,
    status_code TINYINT NOT NULL,
    attributes_json JSON NOT NULL,
    PRIMARY KEY(time_unix_nano, trace_id, span_id),
    INDEX idx_service_time(service_name, time_unix_nano),
    INDEX idx_trace(trace_id, time_unix_nano)
);


CREATE TABLE IF NOT EXISTS metric_points(
    time_unix_nano BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    service_name VARCHAR(255) NOT NULL,
    metric_name VARCHAR(255) NOT NULL,
    metric_type TINYINT NOT NULL, -- 1=sum, 2=gauge, 3=histogram
    value_double DOUBLE NULL,      -- For sum/gauge points
    value_sum DOUBLE NULL,         -- Sum of values for a histogram
    value_count BIGINT NULL,       -- Count of values for a histogram
    buckets_json JSON NULL,        -- Bucket boundaries and counts; NULL for sum/gauge
    attributes_hash CHAR(16) NOT NULL, -- Hex 64-bit hash of attributes
    attributes_json JSON NOT NULL, -- Full attributes

    PRIMARY KEY (time_unix_nano, service_name, metric_name, attributes_hash),
    INDEX idx_service_metric_time (service_name, metric_name, time_unix_nano)
);


CREATE TABLE IF NOT EXISTS logs (
    time_unix_nano BIGINT NOT NULL,
    tenant_id BIGINT NOT NULL,
    service_name VARCHAR(255) NOT NULL,
    severity_number TINYINT NOT NULL,   -- OTLP scale: 1=TRACE...21=FATAL
    severity_text VARCHAR(16) NOT NULL, -- e.g. INFO, ERROR
    body TEXT NOT NULL,                  -- The log message
    trace_id CHAR(32) NULL,              -- If log emitted inside a trace
    span_id CHAR(16) NULL,               -- If log emitted inside a span
    event_id CHAR(36) NOT NULL,          -- UUID generated by Ingestion
    attributes_json JSON NOT NULL,

    PRIMARY KEY (time_unix_nano, service_name, event_id),
    INDEX idx_service_severity_time (service_name, severity_number, time_unix_nano),
    INDEX idx_trace (trace_id, time_unix_nano)
);